services:
  comfyui:
    image: chelorope/runpod-comfyui:0.0.0
    ports:
      - "3001:3000" # ComfyUI
      - "8888:8888" # Jupyter
      - "4040:4040" # Filebrowser
    environment:
      - JUPYTER_PASSWORD=thisismypassword
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
